# Site settings
title: Už máš bakalářku?
tag_text: Už máš bakalářku?
description: Stránka, jejíž bytí závisí na něčem, co zatím není.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
