# Site settings
title: Už máš bakalářku?
tag_text: Solo
description: Stránka, jejíž bytí závisí na něčem, co není.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
